name: CI Workflow

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: node:latest

    services:
      postgres:
        image: postgres:10.8
        env:
          DB_USER: $DB_USER
          DB_PASSWORD: $DB_PASSWORD
          DB_NAME: $DB_NAME
          DB_PORT:  $DB_PORT
          
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install
      
      - name: Install PostgreSQL client
        run: apt-get update && apt-get install -y postgresql-client

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h postgres -p 5432 -U "$DB_USER"; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
      - name: Create Database and User
        run: |
          psql -h postgres -U "$DB_USER" -c "CREATE DATABASE $DB_NAME;"
          psql -h postgres -U "$DB_USER" -c "CREATE ROLE $DB_USER WITH LOGIN PASSWORD '$DB_PASSWORD';"
          psql -h postgres -U "$DB_USER" -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;"
      

      - name: Run Tests
        env:
          DB_USER: $DB_USER
          DB_PASSWORD: $DB_PASSWORD
          DB_NAME: $DB_NAME
          DB_PORT:  $DB_PORT
          DB_HOST: postgres  # Use the service name
        run: |
          npm test --coverage

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage
